#!/usr/bin/env python3
"""Dump every commit message into one markdown file.

The commit log is where a lot of this project's reverse-engineering findings
actually got written down. This flattens the whole history into a single
document so it can be read as one narrative and mined for things that belong
in `docs/`.

Usage:
    python3 tools/dump_commit_log.py                 # -> data/commit-log.md
    python3 tools/dump_commit_log.py -o /tmp/log.md
    python3 tools/dump_commit_log.py --newest-first
    python3 tools/dump_commit_log.py --no-files
"""

import argparse
import subprocess
import sys
from pathlib import Path

# Unit separators: ASCII record/unit separators never appear in commit text.
REC = "\x1e"
FLD = "\x1f"


def git(*args):
    r = subprocess.run(
        ["git", *args], capture_output=True, text=True, cwd=REPO
    )
    if r.returncode != 0:
        sys.exit(f"git {' '.join(args)} failed:\n{r.stderr.strip()}")
    return r.stdout


def commits(newest_first):
    fmt = FLD.join(["%H", "%h", "%ad", "%an", "%s", "%b"]) + REC
    order = [] if newest_first else ["--reverse"]
    out = git("log", *order, "--date=short", f"--pretty=format:{fmt}")
    for rec in out.split(REC):
        rec = rec.strip("\n")
        if not rec:
            continue
        full, short, date, author, subject, body = rec.split(FLD, 5)
        yield full, short, date, author, subject, body.strip()


def files_of(sha):
    # Root commits have no parent, so diff against the empty tree.
    out = git("show", "--pretty=format:", "--name-status", sha)
    return [ln for ln in out.splitlines() if ln.strip()]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", default="data/commit-log.md")
    ap.add_argument("--newest-first", action="store_true",
                    help="default is oldest-first, so it reads as a story")
    ap.add_argument("--no-files", action="store_true",
                    help="omit the changed-file list under each commit")
    args = ap.parse_args()

    rows = list(commits(args.newest_first))
    order = "newest first" if args.newest_first else "oldest first"
    head = git("rev-parse", "--short", "HEAD").strip()

    md = [
        "# Commit log — full history",
        "",
        f"Generated by `tools/dump_commit_log.py` from {len(rows)} commits "
        f"({order}), through `{head}`. Regenerate; don't hand-edit.",
        "",
        "## Index",
        "",
    ]
    for _, short, date, _, subject, _ in rows:
        md.append(f"- `{short}` {date} — {subject}")
    md.append("")

    for full, short, date, author, subject, body in rows:
        md += ["---", "", f"## `{short}` — {subject}", "",
               f"*{date} · {author} · `{full}`*", ""]
        if body:
            md += [body, ""]
        if not args.no_files:
            files = files_of(full)
            if files:
                md += ["<details><summary>Files changed "
                       f"({len(files)})</summary>", "", "```"]
                md += files
                md += ["```", "", "</details>", ""]

    out = Path(args.out)
    if not out.is_absolute():
        out = REPO / out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(md).rstrip() + "\n")
    print(f"{out}: {len(rows)} commits, {out.stat().st_size / 1024:.1f} KB")


REPO = Path(__file__).resolve().parent.parent

if __name__ == "__main__":
    main()
